//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yp_02_trushkin
{
    using System;
    using System.Collections.Generic;
    
    public partial class ads
    {
        public int ad_id { get; set; }
        public System.DateTime publish_date { get; set; }
        public int city_id { get; set; }
        public int user_id { get; set; }
        public int ad_category_id { get; set; }
        public int ad_type_id { get; set; }
        public int ad_status_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public decimal ad_price { get; set; }
        public string ad_image { get; set; }
    
        public virtual ad_categories ad_categories { get; set; }
        public virtual ad_statuses ad_statuses { get; set; }
        public virtual ad_types ad_types { get; set; }
        public virtual cities cities { get; set; }
        public virtual users users { get; set; }
    }
}
